#!/bin/bash

echo updating repositories
apt update > /dev/null 2>&1

echo upgrading system
apt -y upgrade > /dev/null 2>&1

echo installing docker prerequisites
apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common > /dev/null 2>&1

echo adding docker key
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - > /dev/null 2>&1

echo adding docker repositories
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /dev/null 2>&1

echo updating repositories
apt update > /dev/null 2>&1

echo installing docker
apt install -y docker-ce docker-ce-cli containerd.io > /dev/null 2>&1

echo creating containers user
adduser --disabled-password --gecos '' containers > /dev/null 2>&1

echo changing containers user password
echo containers:containers | chpasswd > /dev/null 2>&1

echo adding containers user to containers group
usermod -aG docker containers > /dev/null 2>&1

echo installing additional docker prerequisites
apt-get install -y curl jq avahi-daemon > /dev/null 2>&1

echo installing home assistant and hassio
curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | bash -s > /dev/null 2>&1

echo installing portainer
docker run -d --restart always --name portainer -h portainer -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer:/data portainer/portainer > /dev/null 2>&1

echo installation complete
